name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Build shared
        run: yarn workspace shared build

      - name: Build services
        run: |
          yarn workspace auth-service build
          yarn workspace member-service build
          yarn workspace document-service build
          yarn workspace ai-service build
          yarn workspace payment-service build

      - name: Build frontend
        run: yarn workspace frontend build

      - name: Test
        run: yarn test