name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/taxsahihai-frontend:latest

      - name: Build and push auth-service
        uses: docker/build-push-action@v4
        with:
          context: ./services/auth-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/taxsahihai-auth-service:latest

      - name: Build and push member-service
        uses: docker/build-push-action@v4
        with:
          context: ./services/member-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/taxsahihai-member-service:latest

      - name: Build and push document-service
        uses: docker/build-push-action@v4
        with:
          context: ./services/document-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/taxsahihai-document-service:latest

      - name: Build and push ai-service
        uses: docker/build-push-action@v4
        with:
          context: ./services/ai-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/taxsahihai-ai-service:latest

      - name: Build and push payment-service
        uses: docker/build-push-action@v4
        with:
          context: ./services/payment-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/taxsahihai-payment-service:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Deploy to Kubernetes
        run: |
          cd kubernetes/scripts
          chmod +x deploy.sh
          ./deploy.sh